### ISSUE TITLE
is this purely camera based avoidance and where could I find code for it?

### ISSUE THREAD

**Issue by Heet06** [pab47/pab47.github.io#2]
Hello, I wanted code for obstacle avoidance purely based on camera or even with a lidar, if you could tell me where I can find code it would be much helpful thank you.
https://www.youtube.com/watch?v=Jp8ZNr-G5ag

**Comment by pab47** [comment]
Code: https://github.com/jonathanperthel/PathVision
Report: https://pab47.github.io/reports/Quadruped_vision_report.pdf
Presentation: https://pab47.github.io/reports/Quadruped_vision_presentation.pdf

**Comment by Heet06** [comment]
Thank You sir, it would be a lot helpful for me to implement obstacle avoidance into my project but I had a question that can I use it with a monocular camera instead of a depth camera?

**Comment by pab47** [comment]
This one used intel real-sense which is a RGB-D camera. But I think you can do the same with a RGB camera.

**Comment by Heet06** [comment]
Thank You sir, with normal RGB camera how shall I get the depth element for the algorithm? Should I go with models like MIDAS for getting the depth map?
